### ISSUE TITLE
AP stuck on requires power cycle

### ISSUE THREAD

**Issue by g4bri3lDev** [jjwbruijn/OpenEPaperLink#102]
After (presumably) an update the AP switches from _online_ to _requires power cycle_ . Rebooting via the menu as well as unplugging and replugging it doesn't resolve the problem. It also persists when doing a rollback to the previous firmware/fs again.

![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/7592130/5531443d-14b4-4ab7-aa6d-39dad65566cd)

After boot:
![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/7592130/4456e52c-2654-4d2c-80a4-e1437d86be35)

Serial output after boot:
![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/7592130/f48956dd-8c13-4876-856a-494b2328bfaa)

**Comment by nlimper** [comment]
Looks like it's trying to update the AP firmware (why? I don't know because it's already at 0017, which is the latest). But for some reason it cannot connect to the tag via SPI so it fails to update.

If you delete /AP_FW_Pack.bin from your littlefs partition (using 'edit contentFS' button) and reboot, it wil not attempt anymore to update. If it does have the correct serial communication with the tag, that's enough to let it run again.

But why does the SPI fails to connect, you want to research. Either some soldering error, or the wrong pin definition.
