### ISSUE TITLE
Automatic reconnect

### ISSUE THREAD

**Issue by Draexl** [jjwbruijn/OpenEPaperLink#123]
My tags (with JSON template) no longer automatically connect to the AP after it has been unplugged for a long time.

Process:
I unplug the AP. Three/four days later I connect it to electricity.
Unfortunately, the tags no longer connect even after hours. I have to take out the batteries.

What are the specifications for the Autoconnect? What could I set so that the tags connect automatically?

**Comment by nlimper** [comment]
To save energy, if tags cannot find an access point, they keep trying for a while, but the time between tries gets bigger. 

```
#define INTERVAL_1_TIME 3600UL                 // Try every hour
#define INTERVAL_1_ATTEMPTS 24                 // for 24 attempts (an entire day)
#define INTERVAL_2_TIME 7200UL                 // Try every 2 hours
#define INTERVAL_2_ATTEMPTS 12                 // for 12 attempts (an additional day)
#define INTERVAL_3_TIME 86400UL                // Finally, try every day
```
https://github.com/jjwbruijn/OpenEPaperLink/blob/master/zbs243_Tag_FW/powermgt.h#L35

So, in the end it only wakes up once a day to try to find an AP. This is by design, because searching all channels for an active AP is a task that's not very battery-friendly.
