### ISSUE TITLE
Fonts not consistently vertically aligned when using Json template

### ISSUE THREAD

**Issue by PieterBoeren** [jjwbruijn/OpenEPaperLink#126]
**Describe the bug**
(This might be a documentation issue)

When using different fonts, I noticed that the vertical alignment is not consistent. When using "Bahnschrift", all is well, but when using the plaintext fonts (for example "glasstown"), text is differently aligned, resulting (in my case) text to be (partly) outside the display.

**To Reproduce**
1. Go to the default "jsonstemplate-demo.html"
2. Click on 'Upload',
3. Text appears normal on the display
4. Change the font to "glasstown_nbp_tf" (leave the text the same) and click 'Upload' again
5. Notice the text half in, half out of the display

**Expected behavior**
In this case, I would expect all of the text to be visible on the display

**Comment by nlimper** [comment]
That's right. The small bitmap fonts have their origin at the left bottom corner. The vlw bitmap fonts have their origin at the top left. And the origin of the truetype fonts is as much as possible at the baseline, but that can differ depending on the font. So, it's a bit trial and error. Won't fix.

The use of the different types of fonts is completely different (you will not use a bitmap font for a heading, and no truetype font for plain text, because they don't render very well in small sizes), so it's just something minor. Also, you won't make a new json template every way. I will add it to the wiki documentation.
