### ISSUE TITLE
Feature request: Provide documentation on how to program the tags via cable.

### ISSUE THREAD

**Issue by dreirund** [jjwbruijn/OpenEPaperLink#219]
### Is your feature request related to a problem? Please describe.

For my use case, using an AP set what the tag displays is not desired, instead I want to do it wired.

### Describe the solution you'd like

The tags have some serial lines directly on the PCB. I want to use this. As far as I have heard the OpenEPaperLink firmware supports this. I want to have documentation on how to do it (how to talk to the firmware).

**Comment by jjwbruijn** [comment]
I'm interpreting this as: I want to serve image data to the tag over a serial link instead of 802.15.4. This isn't supported as a part of OpenEPaperLink, nor planned in the immediate future.

See here for more information:
https://github.com/atc1441/ZBS_Flasher/tree/main/custom-firmware/UART_2.9_EPD
