### ISSUE TITLE
Bricking 2.9bw with ota from nanoAp

### ISSUE THREAD

**Issue by Carlin75** [jjwbruijn/OpenEPaperLink#291]
Hi 
I've heard that there's a big risk of bricking the 2.9bw display when you to update the firmware on the display. Is there a chance of fixing that issue on a upcoming firmware update on the nanoAp?

My displays are st-gm29xxf (fw36, needs to be fw39😁)

Or any tips and hits on to how to update firmware over ota😁

**Comment by jjwbruijn** [comment]
If you have a tag-based AP, there's a decent chance to brick a tag running on v0024
If your tag is already running on v0025 or higher, you're safe. Since this issue is caused by a firmware bug on the tag side, there is no way to fix this on the AP side
Just to be complete: This bug can manifest itself on C6-based AP's as well, the chance is a lot smaller though
