### ISSUE TITLE
Board Outline is missing in epapertagjig.zip

### ISSUE THREAD

**Issue by dcbo** [jjwbruijn/OpenEPaperLink#63]
**Describe the bug**
Board Outline is missing in `Hardware/OpenEPaperLink AP and Flasher/PCB/epapertagjig.zip`

I tried to order the board on JlcPCB, 
but after uploading I get the Error:
_Can not identify the board outline_

**To Reproduce**
Go to [jlcpcb](https://cart.jlcpcb.com/quote) and upload the zip file.

**Comment by jjwbruijn** [comment]
Was able to reproduce it, I'm chalking it down as an issue at jlcpcb. 

I just received another order from DirtyPCB's, ordered it from the zip-as-is.

There is extensive milling on this board, so I can imagine it has some problems recognizing the shape. When ordered from DirtyPCB's, some weird triangles appear in the preview. The board itself came out lovely though.

https://dirtypcbs.com/store/designer/details/5798/6612/epapertagjig-zip

Not sure what the problem is, not going to be fix it/troubleshoot it :) I'd simply order it as a 100x100mm board.

Just a note, as it contains a LOT of designs, ordering at JLCPCB is a pretty expensive idea!
